"""Provider-neutral AtMem 2.2 protocol contracts."""

from atmem.contracts.models import (
    AuthorityScope,
    ActionConstraint,
    ContextPackage,
    ContextPackageV2,
    ContextRequest,
    ContextRequestV2,
    EligibleCandidate,
    EligibleCandidateSet,
    ExposureConfirmation,
    ExposureReceipt,
    EpisodeIngestRequest,
    EpisodePart,
    EvidenceNeighborhood,
    EvidencePath,
    FormationReceipt,
    InformationNeed,
    InterpreterIdentity,
    MemoryAdmission,
    MemoryProposal,
    RecallRequest,
    RetrievalBudget,
    SourceBinding,
    SourceCaptureRequest,
    SourceCaptureResult,
    SufficiencyDecision,
)
from atmem.contracts.task_state import (
    ActorRole,
    Assurance,
    BindingResolution,
    ContextDisposition,
    EvidenceRef,
    ExpiryPolicy,
    GovernanceCapability,
    GuardSignal,
    GuardType,
    HostSessionIdentity,
    HostTaskLifecycleRequest,
    HostTaskObservationRequest,
    HostTaskProposalRequest,
    ItemStatus,
    OperationKind,
    Provenance,
    REASON_CODES,
    SessionBinding,
    StepOutcome,
    TaskConstraint,
    TaskContextPackage,
    TaskItem,
    TaskLifecycle,
    TaskOperation,
    TaskProfile,
    TaskStartRequest,
    TaskState,
    TaskStateProposal,
    TransitionDecision,
)
from atmem.contracts.versions import capabilities

_CONTEXT_ENGINE_EXPORTS = {
    "ContextPackageV3",
    "ContextRequestV3",
    "EvidenceObligation",
    "EvidenceRange",
    "FormationReceiptV2",
    "FormationRequestV2",
    "NavigationReceipt",
    "QueryPlan",
    "SufficiencyDecisionV2",
}


def __getattr__(name: str):
    """Load V3 types lazily so the compatibility export cannot form a cycle."""

    if name in _CONTEXT_ENGINE_EXPORTS:
        from atmem.context_engine import contracts as context_contracts

        return getattr(context_contracts, name)
    raise AttributeError(name)

__all__ = [
    "ActorRole",
    "Assurance",
    "AuthorityScope",
    "ActionConstraint",
    "ContextPackage",
    "ContextPackageV2",
    "ContextPackageV3",
    "ContextRequest",
    "ContextRequestV2",
    "ContextRequestV3",
    "EligibleCandidate",
    "EligibleCandidateSet",
    "ExposureConfirmation",
    "ExposureReceipt",
    "EpisodeIngestRequest",
    "EpisodePart",
    "EvidenceNeighborhood",
    "EvidenceObligation",
    "EvidencePath",
    "EvidenceRange",
    "FormationReceipt",
    "FormationReceiptV2",
    "FormationRequestV2",
    "InformationNeed",
    "InterpreterIdentity",
    "MemoryAdmission",
    "MemoryProposal",
    "NavigationReceipt",
    "QueryPlan",
    "RecallRequest",
    "RetrievalBudget",
    "SourceBinding",
    "SourceCaptureRequest",
    "SourceCaptureResult",
    "SufficiencyDecision",
    "SufficiencyDecisionV2",
    "ContextDisposition",
    "EvidenceRef",
    "ExpiryPolicy",
    "GovernanceCapability",
    "GuardSignal",
    "GuardType",
    "ItemStatus",
    "OperationKind",
    "Provenance",
    "REASON_CODES",
    "StepOutcome",
    "TaskConstraint",
    "TaskContextPackage",
    "TaskItem",
    "TaskLifecycle",
    "TaskOperation",
    "TaskProfile",
    "TaskStartRequest",
    "TaskState",
    "TaskStateProposal",
    "TransitionDecision",
    "capabilities",
]
