"""Inactive Hermes directory-plugin installation; never writes host configuration."""
from __future__ import annotations

import ctypes
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import tempfile

from atmem.adapters.hermes.package import plugin_files
from atmem.locking import ProcessFileLock

RECEIPT = ".atmem-install.json"
FORMAT = "atmem-hermes-install-v1"


def _safe_directory(path: Path) -> None:
    info = path.lstat()
    if (not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid()
            or info.st_mode & 0o022):
        raise ValueError("Hermes paths must be owned directories without group/world write access")


def _read(path: Path, limit: int = 1_048_576) -> bytes:
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    try:
        info = os.fstat(fd)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid()
                or info.st_mode & 0o022 or info.st_nlink != 1):
            raise ValueError("Hermes plugin files must be owned, unshared regular files")
        value = os.read(fd, limit + 1)
        if len(value) > limit:
            raise ValueError("Hermes plugin file exceeds size limit")
        return value
    finally:
        os.close(fd)


def _hashes(payload):
    return {name: hashlib.sha256(value).hexdigest() for name, value in payload.items()}


def _home(value: str | Path) -> Path:
    if os.name != "posix" or sys.platform not in {"darwin", "linux"}:
        raise ValueError("Hermes inactive installer is qualified only for macOS/Linux; native Windows is pending")
    path = Path(value).expanduser().absolute()
    if path != path.resolve():
        raise ValueError("Use the resolved Hermes Home path, without symbolic links")
    _safe_directory(path)
    if path == Path(path.anchor) or path == Path.home():
        raise ValueError("Select a dedicated existing Hermes Home, not a filesystem or user root")
    return path


def inspect_install(home: str | Path) -> dict:
    """Read only. No AtMem Home, credentials, RPCs or host config are loaded."""
    home = _home(home)
    parent, target = home / "plugins", home / "plugins" / "atmem"
    payload = plugin_files()
    state = "not_installed"
    if parent.exists() or parent.is_symlink():
        _safe_directory(parent)
    if target.exists() or target.is_symlink():
        _safe_directory(target)
        try:
            receipt = json.loads(_read(target / RECEIPT))
            hashes = receipt["sha256"]
            if receipt.get("format") != FORMAT or set(hashes) != set(payload):
                raise ValueError("invalid receipt")
            entries = {p.name for p in target.iterdir()}
            if entries - set(payload) - {RECEIPT, "__pycache__"}:
                raise ValueError("unexpected payload files")
            cache = target / "__pycache__"
            if cache.exists() or cache.is_symlink():
                _safe_directory(cache)
                for entry in cache.iterdir():
                    if entry.suffix != ".pyc":
                        raise ValueError("unexpected cache file")
                    _read(entry)
            actual = _hashes({name: _read(target / name) for name in payload})
            if actual != hashes:
                raise ValueError("modified payload")
            state = "installed" if actual == _hashes(payload) else "upgrade_required"
        except (OSError, ValueError, KeyError, TypeError):
            state = "conflict"
    return {"hermes_home": str(home), "target": str(target), "state": state,
            "sha256": _hashes(payload), "activation": "not_performed",
            "connection": "not_checked", "runtime_discovery": "verify_in_hermes",
            "next_step": "Restart Hermes dashboard after installation. Keep the current provider selected; scoped connection setup is separate.",
            "changes": [str(target)] if state == "not_installed" else [],
            "integrity_scope": "packaged source hashes; generated bytecode is not authenticated",
            "upgrade_supported": False}


def _publish(stage: Path, target: Path) -> None:
    """Atomic no-replace rename, including when an empty target appears in a race."""
    libc = ctypes.CDLL(None, use_errno=True)
    if sys.platform == "darwin":
        function = getattr(libc, "renamex_np", None)
        if function is None:
            raise RuntimeError("Exclusive rename unavailable; installation refused")
        function.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_uint]
        result = function(os.fsencode(stage), os.fsencode(target), 4)  # RENAME_EXCL
    else:
        function = getattr(libc, "renameat2", None)
        if function is None:
            raise RuntimeError("Exclusive rename unavailable; installation refused")
        function.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint]
        result = function(-100, os.fsencode(stage), -100, os.fsencode(target), 1)  # RENAME_NOREPLACE
    if result:
        error = ctypes.get_errno()
        raise OSError(error, "Exclusive Hermes plugin publication refused")


def _sync_directory(path):
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def install(home: str | Path, *, apply: bool = False) -> dict:
    preview = inspect_install(home)
    if not apply or preview["state"] == "installed":
        return {**preview, "applied": False}
    if preview["state"] != "not_installed":
        raise ValueError("Existing Hermes plugin differs: inspect it first; overwrite/upgrade is not supported")
    parent = Path(preview["target"]).parent
    parent.mkdir(mode=0o700, exist_ok=True)
    _safe_directory(parent)

    def validate_lock(fd):
        info = os.fstat(fd)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid()
                or info.st_nlink != 1 or info.st_mode & 0o077):
            raise ValueError("Unsafe Hermes installer lock")

    with ProcessFileLock(parent / ".atmem-install.lock", validate=validate_lock):
        current = inspect_install(home)
        if current["state"] == "installed":
            return {**current, "applied": False}
        if current["state"] != "not_installed":
            raise ValueError("Hermes installation changed during preview; refusing overwrite")
        # Both native discovery systems skip names starting with double underscores.
        stage = Path(tempfile.mkdtemp(prefix="__atmem_stage_", dir=parent))
        payload = plugin_files()
        receipt = {"format": FORMAT, "sha256": _hashes(payload)}
        payload[RECEIPT] = (json.dumps(receipt, sort_keys=True) + "\n").encode()
        for name, value in payload.items():
            fd = os.open(stage / name, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(fd, "wb") as stream:
                stream.write(value)
                stream.flush()
                os.fsync(stream.fileno())
        _sync_directory(stage)
        _safe_directory(parent)
        _publish(stage, Path(current["target"]))
        _sync_directory(parent)
    return {**inspect_install(home), "applied": True}
